
CREATE OR REPLACE VIEW CAT_FEATURE AS 

	SELECT 	'PIPE'			id,
		    	'PIPE'	   	system_id,
			    'ARC'	  		feature_type
	FROM DUAL
	UNION
	SELECT	'VARC',     	 'VARC',			'ARC'		  FROM DUAL
	UNION
	SELECT	'FONT_ORN', 	 'FOUNTAIN',	'CONNEC'	FROM DUAL
	UNION
	SELECT	'BOCA_REG',		 'GREENTAP',	'CONNEC'	FROM DUAL
	UNION
	SELECT	'PUNT_CAR',		 'GREENTAP',	'CONNEC'	FROM DUAL
	UNION
	SELECT	'FONT',     	 'TAP',      	'CONNEC'	FROM DUAL
  UNION
	SELECT	'ABEURADOR', 	 'TAP',      	'CONNEC'	FROM DUAL
	UNION	
	SELECT	'ESCOMESA',		 'WJOIN', 		'CONNEC'	FROM DUAL
	UNION
	SELECT  'HIDRANT',		 'HYDRANT',		'NODE'		FROM DUAL
	UNION
	SELECT	'CAPTACIO', 	 'SOURCE',		'NODE'		FROM DUAL
	UNION
	SELECT	'BOMBAMENT',	 'PUMP',			'NODE'		FROM DUAL
	UNION	
	SELECT	'COMPTADOR',	 'METER',		  'NODE'		FROM DUAL
	UNION
	SELECT	'DIPOSIT',		 'TANK',			'NODE'		FROM DUAL
	UNION
	SELECT	'UNIO',			   'JUNCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'DERIVACIO',   'JUNCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'CREUAMENT',	 'JUNCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'INICI_FI',		 'JUNCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'TAP',			   'JUNCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'POU_CONN',		 'MANHOLE',		'NODE'		FROM DUAL
	UNION
	SELECT	'POU',			   'WATERWELL',	'NODE'		FROM DUAL
	UNION
	SELECT	'REDUCCIO',		 'REDUCTION',	'NODE'		FROM DUAL
	UNION
	SELECT	'VALVULA',		 'VALVE',		  'NODE'		FROM DUAL
	UNION
	SELECT	'VDESCARREGA', 'VALVE',		  'NODE'		FROM DUAL
	UNION
	SELECT	'VENTOSA',		 'VALVE',		  'NODE'		FROM DUAL
	UNION
	SELECT	'VREGULADORA', 'VALVE',		  'NODE'		FROM DUAL
	ORDER BY 3, 2, 1;
