

CREATE OR REPLACE VIEW REV_T_TAP AS

  SELECT ID_FONT CONNEC_ID, ID_FONT CODE, 1 EXPL_ID, DATA_REV 
  FROM   NA_MATARO.NA_V_FONT 
  WHERE  DATA_REV IS NOT NULL
  UNION
  SELECT ID_FONT CONNEC_ID, ID_FONT CODE, 2 EXPL_ID, DATA_REV 
  FROM   NA_FIGARO.NA_V_FONT 
  WHERE  DATA_REV IS NOT NULL
  UNION
  SELECT ID_FONT CONNEC_ID, ID_FONT CODE, 3 EXPL_ID, DATA_REV 
  FROM   NA_LLISSADEVALL.NA_V_FONT 
  WHERE  DATA_REV IS NOT NULL;


CREATE OR REPLACE VIEW REV_T_GREENTAP AS

  -- NOMÉS NA_MATARO

  SELECT ID_BREG CONNEC_ID, ID_BREG CODE, 1 EXPL_ID, DATA_REV 
  FROM   NA_MATARO.NA_V_BREG 
  WHERE  DATA_REV IS NOT NULL;


CREATE OR REPLACE VIEW REV_T_WJOIN AS

  SELECT ID_ESCO CONNEC_ID, ID_ESCO CODE, 1 EXPL_ID, DDM DATA_REV 
  FROM   NA_MATARO.NA_V_ESCO 
  WHERE  DDM IS NOT NULL
  UNION
  SELECT ID_ESCO CONNEC_ID, ID_ESCO CODE, 2 EXPL_ID, DDM DATA_REV 
  FROM   NA_FIGARO.NA_V_ESCO 
  WHERE  DDM IS NOT NULL
  UNION
  SELECT ID_ESCO CONNEC_ID, ID_ESCO CODE, 3 EXPL_ID, DDM DATA_REV 
  FROM   NA_LLISSADEVALL.NA_V_ESCO 
  WHERE  DDM IS NOT NULL;



CREATE OR REPLACE VIEW REV_T_HYDRANT AS

  -- NOMÉS NA_MATARO

  SELECT ID_BINC CONNEC_ID, ID_BINC CODE, 1 EXPL_ID, INCID_OC, INCID_OM, DATA_DR, DATA_FR, REVI_ESTAT, RACORD_ESTAT
  FROM   NA_MATARO.NA_V_BINC
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR DATA_DR IS NOT NULL OR DATA_FR IS NOT NULL OR REVI_ESTAT IS NOT NULL OR RACORD_ESTAT IS NOT NULL;




CREATE OR REPLACE VIEW REV_T_VALVE AS

  -- NA_MATARO (VALV + VDES + VENT)
  -- NA_FIGARO (VALV + VDES)

  SELECT ID_VALV CONNEC_ID, ID_VALV CODE, 'VALVULA' NODETYPE_ID, 1 EXPL_ID, INCID_OC, INCID_OM, DATA_DR, DATA_FR, REVI_ESTAT
  FROM   NA_MATARO.NA_V_VALV
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR DATA_DR IS NOT NULL OR DATA_FR IS NOT NULL OR REVI_ESTAT IS NOT NULL 
  UNION
  SELECT ID_VDES CONNEC_ID, ID_VDES CODE, 'VDESCARREGA' NODETYPE_ID, 1 EXPL_ID, INCID_OC, INCID_OM, REVI_INICI, REVI_FINAL, REVI_ESTAT
  FROM   NA_MATARO.NA_V_VDES
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR REVI_INICI IS NOT NULL OR REVI_FINAL IS NOT NULL OR REVI_ESTAT IS NOT NULL 
  UNION
  SELECT ID_VENT CONNEC_ID, ID_VENT CODE, 'VENTOSA' NODETYPE_ID, 1 EXPL_ID, INCID_OC, INCID_OM, DATA_DR, DATA_FR, REVI_ESTAT
  FROM   NA_MATARO.NA_V_VENT
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR DATA_DR IS NOT NULL OR DATA_FR IS NOT NULL OR REVI_ESTAT IS NOT NULL 
  
  UNION
  
  SELECT ID_VALV CONNEC_ID, ID_VALV CODE, 'VALVULA' NODETYPE_ID, 1 EXPL_ID, INCID_OC, INCID_OM, DATA_DR, DATA_FR, REVI_ESTAT
  FROM   NA_FIGARO.NA_V_VALV
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR DATA_DR IS NOT NULL OR DATA_FR IS NOT NULL OR REVI_ESTAT IS NOT NULL 
  UNION
  SELECT ID_VDES CONNEC_ID, ID_VDES CODE, 'VDESCARREGA' NODETYPE_ID, 1 EXPL_ID, INCID_OC, INCID_OM, DATA_DR, DATA_FR, REVI_ESTAT
  FROM   NA_FIGARO.NA_V_VDES
  WHERE  INCID_OC IS NOT NULL OR INCID_OM IS NOT NULL OR DATA_DR IS NOT NULL OR DATA_FR IS NOT NULL OR REVI_ESTAT IS NOT NULL;



CREATE OR REPLACE VIEW REV_T_SAMPLEPOINT AS

  -- NOMÉS NA_MATARO

  SELECT ID_MOST CONNEC_ID, ID_MOST CODE, 1 EXPL_ID, DATA_REV 
  FROM   NA_MATARO.NA_V_MOST
  WHERE  DATA_REV IS NOT NULL;