
-- ABASTAMENT

CREATE OR REPLACE VIEW GW_MIGRA_NETAQUA.EXT_ADDRESS AS

  SELECT ROW_NUMBER() OVER (ORDER BY EXPL_ID, STREETAXIS_ID, ORDRE ) ID,
         T.MUNI_ID, T.POSTCODE, T.STREETAXIS_ID, T.POSTNUMBER, PLOT_ID, T.THE_GEOM, T.EXPL_ID
  FROM (
    SELECT 1                                 MUNI_ID,
           NULL                              POSTCODE,
           CAST(CODI_CARRER AS VARCHAR(15))  STREETAXIS_ID,
           NUMERO                            POSTNUMBER,
           TO_NUMBER( regexp_replace(NUMERO, '[^0-9]', '') ) ORDRE,
           NULL                              PLOT_ID,
           MDSYS.SDO_GEOMETRY(2001,25831,MDSYS.SDO_POINT_TYPE( X_COORD, Y_COORD, null), null, null) THE_GEOM,
           1                                 EXPL_ID
    FROM   NA_MATARO.CAT_T_NUM_POSTALS
  )  T;


-- CLAVEGUERAM

CREATE OR REPLACE VIEW GW_MIGRA_NETSANEA.EXT_ADDRESS AS

  SELECT ROW_NUMBER() OVER (ORDER BY EXPL_ID, STREETAXIS_ID, ORDRE ) ID,
         T.MUNI_ID, T.POSTCODE, T.STREETAXIS_ID, T.POSTNUMBER, PLOT_ID, T.THE_GEOM, T.EXPL_ID
  FROM (
    SELECT 1                                 MUNI_ID,
           NULL                              POSTCODE,
           CAST(CODI_CARRER AS VARCHAR(15))  STREETAXIS_ID,
           NUMERO                            POSTNUMBER,
           TO_NUMBER( regexp_replace(NUMERO, '[^0-9]', '') ) ORDRE,
           NULL                              PLOT_ID,
           MDSYS.SDO_GEOMETRY(2001,25831,MDSYS.SDO_POINT_TYPE( X_COORD, Y_COORD, null), null, null) THE_GEOM,
           1                                 EXPL_ID
    --FROM   NA_MATARO.CAT_T_NUM_POSTALS
    FROM   NA_MATARO.CAT_T_NUM_POSTALS

  )  T;


  /*

  NA. CAT vs GEO

  SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'CAT_T_CARRER' TAULA
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'BASE_EIX_CARRER'
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T1.CODI IS NULL;
  
  NA. CAT vs NOMENCLATOR
  
  [OK] SELECT T2.*
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN ZZ_NOMENCLATOR T2 ON T1.CODI = T2.CODI_CARRER
  WHERE  T1.CODI IS NULL
    AND  T2.CODI_CARRER IS NOT NULL;


  NA vs NS :: OK

  [OK] SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'NA_MATARO' TAULA
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T2.CODI IS NULL
  UNION
  SELECT T2.CODI, T2.TIPUS_VIA || ' ' || T2.AUX || ' ' || T2.NOM, 'NS_MATARO'
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T1.CODI IS NULL;

  [OK] SELECT T1.* , T2.*
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T1.NOM <> T2.NOM;

  ---

  [ok] SELECT T1.CARRER_ID, T1.CARRER_NOM, 'NA_MATARO' TAULA
  FROM   NA_MATARO.BASE_EIX_CARRER T1
           LEFT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CARRER_ID = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'NS_MATARO'
  FROM   NA_MATARO.BASE_EIX_CARRER T1
           RIGHT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CARRER_ID = T2.CARRER_ID
  WHERE  T1.CARRER_ID IS NULL;


  NS. CAT vs GEO

  SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'CAT_T_CARRER' TAULA
  FROM   NS_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'BASE_EIX_CARRER'
  FROM   NS_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T1.CODI IS NULL;


  NS. CAT vs NOMENCLATOR
  
  [OK] SELECT T2.*
  FROM   NS_MATARO.CAT_T_CARRER T1
           RIGHT JOIN ZZ_NOMENCLATOR T2 ON T1.CODI = T2.CODI_CARRER
  WHERE  T1.CODI IS NULL
    AND  T2.CODI_CARRER IS NOT NULL;

  */
  
  