
-- ABASTAMENT

CREATE OR REPLACE VIEW GW_MIGRA_NETAQUA.EXT_STREETAXIS AS

  SELECT CAST(T1.CODI AS VARCHAR(15))  ID,
         T1.CODI                       CODE,
         T1.TIPUS_VIA                  TYPE,
         T1.NOM                        NAME,
         T1.AUX                        TEXT,
         T2.EIX_CARRER_GEO             THE_GEOM,
         1                             EXPL_ID,
         1                             MUNI_ID
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  ORDER BY EXPL_ID, ID, NAME;


-- CLAVEGUERAM

CREATE OR REPLACE VIEW GW_MIGRA_NETSANEA.EXT_STREETAXIS AS

  SELECT T1.CODI                    ID,
         T1.CODI                    CODE,
         T1.TIPUS_VIA               TYPE,
         T1.NOM                     NAME,
         T1.AUX                     TEXT,
         T2.EIX_CARRER_GEO          THE_GEOM,
         1                          EXPL_ID,
         1                          MUNI_ID
  --FROM   NS_MATARO.CAT_T_CARRER T1
  --         LEFT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  ORDER BY EXPL_ID, ID, NAME;


  /*

  NA. CAT vs GEO

  SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'CAT_T_CARRER' TAULA
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'BASE_EIX_CARRER'
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NA_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T1.CODI IS NULL;
  
  NA. CAT vs NOMENCLATOR
  
  [OK] SELECT T2.*
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN ZZ_NOMENCLATOR T2 ON T1.CODI = T2.CODI_CARRER
  WHERE  T1.CODI IS NULL
    AND  T2.CODI_CARRER IS NOT NULL;


  NA vs NS :: OK

  [OK] SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'NA_MATARO' TAULA
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T2.CODI IS NULL
  UNION
  SELECT T2.CODI, T2.TIPUS_VIA || ' ' || T2.AUX || ' ' || T2.NOM, 'NS_MATARO'
  FROM   NA_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T1.CODI IS NULL;

  [OK] SELECT T1.* , T2.*
  FROM   NA_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.CAT_T_CARRER T2 ON T1.CODI = T2.CODI
  WHERE  T1.NOM <> T2.NOM;

  ---

  [ok] SELECT T1.CARRER_ID, T1.CARRER_NOM, 'NA_MATARO' TAULA
  FROM   NA_MATARO.BASE_EIX_CARRER T1
           LEFT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CARRER_ID = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'NS_MATARO'
  FROM   NA_MATARO.BASE_EIX_CARRER T1
           RIGHT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CARRER_ID = T2.CARRER_ID
  WHERE  T1.CARRER_ID IS NULL;


  NS. CAT vs GEO

  SELECT T1.CODI, T1.TIPUS_VIA || ' ' || T1.AUX || ' ' || T1.NOM, 'CAT_T_CARRER' TAULA
  FROM   NS_MATARO.CAT_T_CARRER T1
           LEFT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T2.CARRER_ID IS NULL
  UNION
  SELECT T2.CARRER_ID, T2.CARRER_NOM, 'BASE_EIX_CARRER'
  FROM   NS_MATARO.CAT_T_CARRER T1
           RIGHT JOIN NS_MATARO.BASE_EIX_CARRER T2 ON T1.CODI = T2.CARRER_ID
  WHERE  T1.CODI IS NULL;


  NS. CAT vs NOMENCLATOR
  
  [OK] SELECT T2.*
  FROM   NS_MATARO.CAT_T_CARRER T1
           RIGHT JOIN ZZ_NOMENCLATOR T2 ON T1.CODI = T2.CODI_CARRER
  WHERE  T1.CODI IS NULL
    AND  T2.CODI_CARRER IS NOT NULL;

  */


  /*
    CAMPS ABASTAMENT
    ================


  // NOTA: PEL FIGARÓ NO EXISTEIX NA_V_MOST NI NA_V_VALV.SITUACIO_REGU [!!]

  SELECT T1.ID_MOST ID_ELEM, T1.CARRER1 ID_CARRER, T2.NOM NOM, 'MOST_CARRER1' TIPUS
  FROM   NA_V_MOST T1
           LEFT JOIN CAT_T_CARRER T2 ON T1.CARRER1 = T2.CODI || ',' || T2.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER1 IS NOT NULL AND T2.NOM IS NULL)
  UNION
  SELECT T1.ID_MOST, T1.CARRER2 ID_CARRER, T3.NOM, 'MOST_CARRER2'
  FROM   NA_V_MOST T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL)
  UNION
  SELECT T1.ID_FONT, T1.CARRER1 ID_CARRER, T3.NOM, 'FONT_CARRER1'
  FROM   NA_V_FONT T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER1 = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER1 IS NOT NULL AND T3.NOM IS NULL)
  UNION
  SELECT T1.ID_FONT, T1.CARRER2 ID_CARRER, T3.NOM, 'FONT_CARRER2'
  FROM   NA_V_FONT T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL) AND T1.CARRER2 <> '0'
  UNION
  SELECT T1.ID_FOOR, T1.CARRER1 ID_CARRER, T3.NOM, 'FOOR_CARRER1'
  FROM   NA_V_FOOR T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER1 = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER1 IS NOT NULL AND T3.NOM IS NULL)
  UNION
  SELECT T1.ID_FOOR, T1.CARRER2 ID_CARRER, T3.NOM, 'FOOR_CARRER2'
  FROM   NA_V_FOOR T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL)
  UNION
  SELECT T1.ID_VALV, T1.SITUACIO_REGU ID_CARRER, T3.NOM, 'VALV_SITUACIO_REGU'
  FROM   NA_V_VALV T1
           LEFT JOIN CAT_T_CARRER T3 ON T1.SITUACIO_REGU = T3.CODI || ',' || T3.MUN_ID_MUNICIPI
  WHERE  (T1.SITUACIO_REGU IS NOT NULL AND T3.NOM IS NULL)
  ORDER BY ID_CARRER;


  [mataró]
  SELECT * 
  FROM   NA_T_DADES_ELEMENT
  WHERE  VALOR NOT LIKE '%,1'
    AND  VALOR <> '0'
    AND  (
  (CAR_ID_CARACTERISTICA= 22 AND CAR_TIE_ID_TIPUS='VALV') OR
  (CAR_ID_CARACTERISTICA= 14 AND CAR_TIE_ID_TIPUS='FONT') OR
  (CAR_ID_CARACTERISTICA= 13 AND CAR_TIE_ID_TIPUS='FONT') OR
  (CAR_ID_CARACTERISTICA= 12 AND CAR_TIE_ID_TIPUS='FOOR') OR
  (CAR_ID_CARACTERISTICA= 11 AND CAR_TIE_ID_TIPUS='FOOR') OR
  (CAR_ID_CARACTERISTICA= 5  AND CAR_TIE_ID_TIPUS='MOST') OR
  (CAR_ID_CARACTERISTICA= 4  AND CAR_TIE_ID_TIPUS='MOST')
  );

  [figaró]+[lliçà de vall]
  SELECT * 
  FROM   NA_T_DADES_ELEMENT
  WHERE  VALOR NOT LIKE '%,1'
    AND  VALOR <> '0'
    AND  (
  (CAR_ID_CARACTERISTICA=  2 AND CAR_TIE_ID_TIPUS='FOOR') OR
  (CAR_ID_CARACTERISTICA=  5 AND CAR_TIE_ID_TIPUS='FOOR') OR
  (CAR_ID_CARACTERISTICA= 10 AND CAR_TIE_ID_TIPUS='FONT') OR
  (CAR_ID_CARACTERISTICA= 11 AND CAR_TIE_ID_TIPUS='FONT')
  );



*/

/*
  CAMPS CLAVEGUERAM
  =================

SELECT T1.ID_NODE ID_ELEM, T1.CARRER ID_CARRER, T2.NOM NOM, 'NODE_CARRER1' TIPUS
FROM   CL_T_NODE T1
         LEFT JOIN CAT_T_CARRER T2 ON T1.CARRER = T2.CODI 
WHERE  (T1.CARRER IS NOT NULL AND T2.NOM IS NULL)
UNION
SELECT T1.ID_NODE, T1.CARRER2 ID_CARRER, T3.NOM, 'NODE_CARRER2'
FROM   CL_T_NODE T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI 
WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL)
UNION
SELECT T1.ID_TRAM, T1.CARRER ID_CARRER, T3.NOM, 'TRAM_CARRER1'
FROM   CL_T_TRAM T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER = T3.CODI 
WHERE  (T1.CARRER IS NOT NULL AND T3.NOM IS NULL)
UNION
SELECT T1.ID_TRAM, T1.CARRER2 ID_CARRER, T3.NOM, 'TRAM_CARRER2'
FROM   CL_T_TRAM T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI
WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL)
ORDER BY ID_CARRER;


// NOTA: PEL FIGARÓ NO EXISTEIX CL_V_MOSTREIG [!!]

SELECT T1.ID_EMBORNAL ID_ELEM, T1.EMBCAR ID_CARRER, T3.NOM, 'EMBO_CARRER'
FROM   CL_V_EMBORNAL T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.EMBCAR = T3.CODI
WHERE  (T1.EMBCAR IS NOT NULL AND T3.NOM IS NULL) AND T1.EMBCAR <> '0'
UNION
SELECT T1.ID_REIXA, T1.REICAR ID_CARRER, T3.NOM, 'REIX_CARRER'
FROM   CL_V_REIXA T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.REICAR = T3.CODI
WHERE  (T1.REICAR IS NOT NULL AND T3.NOM IS NULL) AND T1.REICAR <> '0'
UNION
SELECT T1.ID_CLAVEGUERO, T1.CLACAR ID_CARRER, T3.NOM, 'CLAV_CARRER'
FROM   CL_V_CLAVEGUERO T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.CLACAR = T3.CODI
WHERE  (T1.CLACAR IS NOT NULL AND T3.NOM IS NULL)
UNION
SELECT T1.ID_MOSTREIG ID_ELEM, T1.CARRER1 ID_CARRER, T2.NOM NOM, 'MOST_CARRER1' TIPUS
FROM   CL_V_MOSTREIG T1
         LEFT JOIN CAT_T_CARRER T2 ON T1.CARRER1 = T2.CODI 
WHERE  (T1.CARRER1 IS NOT NULL AND T2.NOM IS NULL)
UNION
SELECT T1.ID_MOSTREIG, T1.CARRER2 ID_CARRER, T3.NOM, 'MOST_CARRER2'
FROM   CL_V_MOSTREIG T1
         LEFT JOIN CAT_T_CARRER T3 ON T1.CARRER2 = T3.CODI 
WHERE  (T1.CARRER2 IS NOT NULL AND T3.NOM IS NULL)
ORDER BY ID_CARRER;

*/