
CREATE OR REPLACE VIEW CAT_BRAND_MODEL AS 

	SELECT 	DISTINCT REPLACE(UPPER(TRIM(SUBSTR(T3.DESCR_VR_MODEL, INSTR(T3.DESCR_VR_MODEL,' - ')+3))),' ','_') id,
    	   	TRIM(SUBSTR(T2.DESCR_VR_MARCA, INSTR(T2.DESCR_VR_MARCA,' - ')+3))                                  catbrand_id, 
       		REPLACE(TRIM(SUBSTR(T3.DESCR_VR_MODEL, INSTR(T3.DESCR_VR_MODEL,' - ')+3)),'_XX',' - ??')           descript, 
       		null                                                                                               link
	FROM   NA_MATARO.NA_V_VALV T1
    	     LEFT JOIN NA_MATARO.CAT2_T_VALV_REGU_MARCA T2 ON T1.MARCA = T2.ID_VR_MARCA
        	 LEFT JOIN NA_MATARO.CAT2_T_VALV_REGU_MODEL T3 ON T1.MODEL = T3.ID_VR_MODEL
	WHERE  T1.MODEL IS NOT NULL
	
  UNION
	
  SELECT 	DISTINCT REPLACE(UPPER(TRIM(CAST(T3.ID_COMP_FAB AS VARCHAR2(20)))),' ','_'),
    	   	REPLACE(INITCAP(CAST(T2.ID_COMP_MARCA AS VARCHAR2(10))),' '), 
       		TRIM(CAST(T3.ID_COMP_FAB AS VARCHAR2(20))), 
       		null
	FROM   NA_MATARO.NA_V_COMP T1
    	     LEFT JOIN NA_MATARO.CAT2_T_COMP_MARCA T2 ON T1.MARCA = T2.ID_COMP_MARCA
        	 LEFT JOIN NA_MATARO.CAT2_T_COMP_FAB T3 ON T1.CODI_FAB = T3.ID_COMP_FAB
	WHERE  T1.CODI_FAB IS NOT NULL
  
  UNION
  
  SELECT  REPLACE(UPPER(TRIM(SUBSTR(T1.FONT_TIPUS, INSTR(T1.FONT_TIPUS,' - ')+3))),' ','_'),
          null,
          T1.FONT_TIPUS_MODEL,
          null
  FROM    NA_MATARO.CAT2_T_FONT_TIPUS T1
  WHERE   T1.ID_FONT_TIPUS <> 'MO'
  
  UNION
  
  SELECT  'A', null, 'Alta', null       FROM DUAL
  UNION
  SELECT  'P', null, 'Principal', null  FROM DUAL
  UNION
  SELECT  'S', null, 'Secundària', null FROM DUAL
  
  UNION
  
  -- ELEMENT : OPER
  
  SELECT 'GM', 'Calpeda', 'GM', null FROM DUAL
  UNION
  SELECT 'MPC_7', 'Calpeda', 'MPC 7', null FROM DUAL
  UNION
  SELECT 'VGV750AS', 'Espa', 'VGV750AS', null FROM DUAL
  UNION
  SELECT 'IN-200_240', 'Itur', 'IN-200/240', null FROM DUAL
  UNION
  SELECT 'IN-150_250', 'Itur', 'IN-150/250', null FROM DUAL
  UNION
  SELECT 'KS150B', 'Kripsol', 'KS150B', null FROM DUAL
  UNION
  SELECT 'KS150T', 'Kripsol', 'KS150T', null FROM DUAL
  UNION
  SELECT 'TOP1', 'Pedrollo', 'TOP1', null FROM DUAL
  UNION
  SELECT 'TOP2', 'Pedrollo', 'TOP2', null FROM DUAL
  UNION
  SELECT 'TOP3', 'Pedrollo', 'TOP3', null FROM DUAL
  UNION
  SELECT 'SUPERSTAR_E3000_F2', 'Praher', 'SUPERSTAR E-3000/F2', null FROM DUAL
  UNION
  SELECT 'DPT-25', 'Prat', 'DPT-25', null FROM DUAL
  UNION
  SELECT 'FP_100_55', 'Prat', 'FP 100/55', null FROM DUAL
  UNION
  SELECT 'WINNER_50T', 'Saci', 'WINNER 50T', null FROM DUAL
  UNION
  SELECT 'CF2-750', 'Saci', 'CF2-750', null FROM DUAL
  UNION
  SELECT 'KOMPACT_AMS200', 'Seko', 'KOMPACT AMS200', null FROM DUAL
  UNION
  SELECT 'TEKNA_TPR_EM00136063', 'Seko', 'TEKNA TPR EM00136063', null FROM DUAL
  UNION
  SELECT 'KPS02PM0000', 'Seko', 'KPS02PM0000', null FROM DUAL
  UNION
  SELECT 'KONTROL_800', 'Seko', 'KONTROL 800', null FROM DUAL
  UNION
  SELECT 'P-65-160-C', 'Veneto', 'P-65-160-C', null FROM DUAL
  UNION
  SELECT 'FP_400', 'Veneto', 'FP 400', null FROM DUAL
  UNION
  SELECT 'FP_750', 'Veneto', 'FP 750', null FROM DUAL
  UNION
  SELECT 'RGM-20', 'Veneto', 'RGM-20', null FROM DUAL
  UNION
  SELECT 'DRBLUE_75M', 'Zenit', 'DRBLUE 75M', null FROM DUAL
  
	ORDER BY 2, 1;


/* CONSULTA PER MIGRACIÃ“ */

CREATE OR REPLACE VIEW TMP_CAT_BRAND_MODEL AS 

	SELECT 	DISTINCT REPLACE(UPPER(TRIM(SUBSTR(T3.DESCR_VR_MODEL, INSTR(T3.DESCR_VR_MODEL,' - ')+3))),' ','_') id,
    	   	TRIM(SUBSTR(T2.DESCR_VR_MARCA, INSTR(T2.DESCR_VR_MARCA,' - ')+3))                                  catbrand_id, 
          REPLACE(TRIM(SUBSTR(T3.DESCR_VR_MODEL, INSTR(T3.DESCR_VR_MODEL,' - ')+3)),'_XX',' - ??')           descript, 
       		null                                                                                               link,
       		T2.ID_VR_MARCA                                                                                     id_marca_netaqua,
       		T3.ID_VR_MODEL                                                                                     id_model_netaqua
	FROM   NA_MATARO.NA_V_VALV T1
    	     LEFT JOIN NA_MATARO.CAT2_T_VALV_REGU_MARCA T2 ON T1.MARCA = T2.ID_VR_MARCA
        	 LEFT JOIN NA_MATARO.CAT2_T_VALV_REGU_MODEL T3 ON T1.MODEL = T3.ID_VR_MODEL
	WHERE  T1.MODEL IS NOT NULL
	UNION
	SELECT 	DISTINCT REPLACE(UPPER(TRIM(CAST(T3.ID_COMP_FAB AS VARCHAR2(20)))),' ','_'),
    	   	REPLACE(INITCAP(CAST(T2.ID_COMP_MARCA AS VARCHAR2(10))),' '), 
       		TRIM(CAST(T3.ID_COMP_FAB AS VARCHAR2(20))), 
       		null,
       		CAST(T2.ID_COMP_MARCA AS VARCHAR2(20)),
       		CAST(T3.ID_COMP_FAB AS VARCHAR2(20))
	FROM   NA_MATARO.NA_V_COMP T1
    	     LEFT JOIN NA_MATARO.CAT2_T_COMP_MARCA T2 ON T1.MARCA = T2.ID_COMP_MARCA
        	 LEFT JOIN NA_MATARO.CAT2_T_COMP_FAB T3 ON T1.CODI_FAB = T3.ID_COMP_FAB
	WHERE  T1.CODI_FAB IS NOT NULL
	ORDER BY CATBRAND_ID, ID;

