
CREATE OR REPLACE VIEW CAT_BRAND AS 

	SELECT  TRIM(SUBSTR(DESCR_VR_MARCA, INSTR(DESCR_VR_MARCA,' - ')+3)) id,
	        TRIM(SUBSTR(DESCR_VR_MARCA, INSTR(DESCR_VR_MARCA,' - ')+3)) descript,   
			    null	        			                                        link
	FROM	NA_MATARO.CAT2_T_VALV_REGU_MARCA
  
  UNION
  
	SELECT  REPLACE(INITCAP(CAST(ID_COMP_MARCA AS VARCHAR2(10))),' '),
	    		REPLACE(INITCAP(CAST(ID_COMP_MARCA AS VARCHAR2(10))),' '),
			    null
	FROM    NA_MATARO.CAT2_T_COMP_MARCA
  
	-- ARQUETA VALV
  
	UNION
	SELECT  DISTINCT VALVULA_ARQUETA_MARCA,
	  	    VALVULA_ARQUETA_MARCA,
		      null
	FROM    NA_MATARO.CAT2_T_VALV_ARQUETA
  WHERE   VALVULA_ARQUETA_MARCA IS NOT NULL
  
  -- BREG
  UNION
	SELECT  DISTINCT BOCAREG_TIPUS_MARCA,
	  	    BOCAREG_TIPUS_MARCA,
		    	null
	FROM    NA_MATARO.CAT2_T_BREG_TIPUS
  WHERE   BOCAREG_TIPUS_MARCA IS NOT NULL
  
  -- BINC
  UNION
	SELECT  DISTINCT BOCAINC_TIPUS_MARCA,
	 	      BOCAINC_TIPUS_MARCA,
			    null
	FROM    NA_MATARO.CAT2_T_BINC_TIPUS
  WHERE   BOCAINC_TIPUS_MARCA IS NOT NULL
  
  -- VENT
  UNION
	SELECT  DISTINCT VENTOSA_TIPUS_MARCA,
		      VENTOSA_TIPUS_MARCA,
			    null
	FROM    NA_MATARO.CAT2_T_VENT_TIPUS
  WHERE   VENTOSA_TIPUS_MARCA IS NOT NULL
  
  -- AFEGEIX ALTRES MARQUES QUE CONSTIN AL CATÀLEG DE NODES
  UNION
  SELECT DISTINCT 
         CASE
           WHEN BRAND <> 'AVK' THEN INITCAP(BRAND)
           ELSE BRAND
         END,
         CASE
           WHEN BRAND <> 'AVK' THEN INITCAP(BRAND)
           ELSE BRAND
         END,
	       null
	FROM   CAT_NODE
	WHERE  BRAND IS NOT NULL
  
  -- FONT : AIXETA
  
  UNION
  SELECT  INITCAP( TRIM(SUBSTR(FONT_AIXETA, INSTR(FONT_AIXETA,' - ')+3)) ),
	        INITCAP(TRIM(SUBSTR(FONT_AIXETA, INSTR(FONT_AIXETA,' - ')+3)) ),
          null
	FROM	  NA_MATARO.CAT2_T_FONT_AIXETA
  WHERE   ID_FONT_AIXETA <> 'AL'
  
	ORDER BY 1;


/* TAULA PER CONVERSIÃ“ DE VALORS */

CREATE OR REPLACE VIEW TMP_CAT_BRAND AS 

	SELECT  TRIM(SUBSTR(DESCR_VR_MARCA, INSTR(DESCR_VR_MARCA,' - ')+3)) id,
	        TRIM(SUBSTR(DESCR_VR_MARCA, INSTR(DESCR_VR_MARCA,' - ')+3)) descript,   
			null				                                        link,
			ID_VR_MARCA                                                 id_netaqua
	FROM	NA_MATARO.CAT2_T_VALV_REGU_MARCA
  	UNION
	SELECT  REPLACE(INITCAP(CAST(ID_COMP_MARCA AS VARCHAR2(10))),' '),
			REPLACE(INITCAP(CAST(ID_COMP_MARCA AS VARCHAR2(10))),' '),
			null,
			CAST(ID_COMP_MARCA AS VARCHAR2(10))
	FROM NA_MATARO.CAT2_T_COMP_MARCA
  	ORDER BY 1;
