
-- NA_DIPO.FUNCIO		CAT2_T_DIPO_FUNCIO
-- NA_VALV.FUNCIO		CAT2_T_VALV_FUNCIO

CREATE OR REPLACE VIEW GW_MIGRA_NETAQUA.MAN_TYPE_FUNCTION AS 

	SELECT	ROWNUM			          id,
          T1.*
	FROM (

		SELECT 	ID_DIPO_FUNCIO		  function_type,
            'NODE'				      feature_type,
            'TANK'     		      featurecat_id,
            DESCR_DIPO_FUNCIO	  observ
		FROM    NA_MATARO.CAT2_T_DIPO_FUNCIO

		UNION

		SELECT  ID_VALV_FUNCIO, 'NODE', 'VALVE', INITCAP(ID_VALV_FUNCIO)
		FROM    NA_MATARO.CAT2_T_VALV_FUNCIO
    WHERE   ID_VALV_FUNCIO NOT IN ('-', 'REGULADORA')
   
    UNION   
    
    SELECT 'OBR', 'CONNEC', 'ESCOMESA', 'Obres' FROM DUAL
    UNION
    SELECT 'INC', 'CONNEC', 'ESCOMESA', 'Incendis' FROM DUAL
    UNION
    SELECT 'RAP', 'CONNEC', 'ESCOMESA', 'Reg Ajuntament Parcs' FROM DUAL
    UNION
    SELECT 'RRP', 'CONNEC', 'ESCOMESA', 'Reg Privat' FROM DUAL
    UNION
    SELECT 'FOP', 'CONNEC', 'ESCOMESA', 'Font Pública' FROM DUAL
    UNION
    SELECT 'RAA', 'CONNEC', 'ESCOMESA', 'Reg Ajuntament Altres' FROM DUAL  

		ORDER BY 2, 3, 1

	) T1
  
  UNION 
    SELECT 12, 'SALA_COM',  'ELEMENT', 'SALA', 'de Comandament' FROM DUAL
    UNION
    SELECT 13, 'SALA_CLOR', 'ELEMENT', 'SALA', 'de Cloració' FROM DUAL
    UNION
    SELECT 14, 'SALA_QELE', 'ELEMENT', 'SALA', 'de Quadre Elèctric' FROM DUAL
    UNION
    SELECT 15, 'BDOS_ACID', 'ELEMENT', 'BOMBA_DOSI', 'd''Àcid' FROM DUAL
    UNION
    SELECT 16, 'BDOS_ACPH', 'ELEMENT', 'BOMBA_DOSI', 'd''Àcid i Analitzadora de PH' FROM DUAL
    UNION
    SELECT 17, 'BDOS_CLOR', 'ELEMENT', 'BOMBA_DOSI', 'de Clor' FROM DUAL
    UNION
    SELECT 18, 'BMB_IMP',   'ELEMENT', 'BOMBA', 'Impulsió' FROM DUAL
    UNION
    SELECT 19, 'BMB_REC',   'ELEMENT', 'BOMBA', 'Recirculació' FROM DUAL
    UNION
    SELECT 20, 'BMB_ESG',   'ELEMENT', 'BOMBA', 'Esgotament' FROM DUAL
    UNION
    SELECT 21, 'VALV_MANU', 'ELEMENT', 'VALV_6VIES', 'Manual' FROM DUAL
    UNION
    SELECT 22, 'VALV_AUTO', 'ELEMENT', 'VALV_6VIES', 'Automàtica' FROM DUAL
    UNION
    SELECT 23, 'ANA_CLOR',  'ELEMENT', 'ANALITZADOR', 'de Clor lliure' FROM DUAL
    UNION
    SELECT 24, 'ANA_CLPH',  'ELEMENT', 'ANALITZADOR', 'de Clor lliure i PH' FROM DUAL;
	
